# Numpy

In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
a=np.array([(1,2,3),(4,5,6)])
a

array([[1, 2, 3],
       [4, 5, 6]])

## Numpy Opeation


In [5]:
a=np.array([(1,2,3),(4,5,6)])
a.ndim

2

In [6]:
a=np.array([(1,2,3),(4,5,6)])
a.itemsize

4

In [7]:
a=np.array([(1,2,3),(4,5,6)])
a.dtype

dtype('int32')

In [8]:
a=np.array([(1,2,3),(4,5,6)])
a.shape

(2, 3)

In [9]:
a=np.array([(1,2,3),(4,5,6)])
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
a=np.array([(1,2,3),(4,5,6)])
a[0,2]

3

In [11]:
a=np.array([(1,2,3),(4,5,6)])
a[0:,2]

array([3, 6])

In [12]:
a=np.array([(1,2,3),(4,5,6)])
a[0:2,1]

array([2, 5])

In [14]:
a=np.linspace(1,3,10)
a

array([1.        , 1.22222222, 1.44444444, 1.66666667, 1.88888889,
       2.11111111, 2.33333333, 2.55555556, 2.77777778, 3.        ])

In [17]:
a=np.array([1,2,3])
a.max()
a.min()
a.sum()

6

In [18]:
a=np.array([(1,2,3),(4,5,6)])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
a=np.array([(1,2,3),(4,5,6)])
a.sum(axis=0)

array([5, 7, 9])

In [20]:
a=np.array([(1,2,3),(4,5,6)])
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [21]:
x=np.array([(1,2,3),(4,5,6)])
y=np.array([(1,2,3),(4,5,6)])
x+y

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [22]:
x=np.array([(1,2,3),(4,5,6)])
y=np.array([(1,2,3),(4,5,6)])
x-y

array([[0, 0, 0],
       [0, 0, 0]])

In [23]:
x=np.array([(1,2,3),(4,5,6)])
y=np.array([(1,2,3),(4,5,6)])
x*y

array([[ 1,  4,  9],
       [16, 25, 36]])

In [24]:
x=np.array([(1,2,3),(4,5,6)])
y=np.array([(1,2,3),(4,5,6)])
x/y

array([[1., 1., 1.],
       [1., 1., 1.]])

###  Vertical Stacking


In [26]:
x=np.array([(1,2,3),(4,5,6)])
y=np.array([(1,2,3),(4,5,6)])
np.vstack((x,y))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [27]:
x=np.array([(1,2,3),(4,5,6)])
y=np.array([(1,2,3),(4,5,6)])
np.hstack((x,y))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])